### ISSUE TITLE
http://www.cs.toronto.edu/~jasper/software.htmlLink broken: 

### ISSUE THREAD

**Issue by nouiz** [JasperSnoek/spearmint#23]
On the main github page, their is this link that is broken:

http://www.cs.toronto.edu/~jasper/software.html

**Comment by Summertaste** [comment]
http://www.cs.toronto.edu/~jasper/software.html
The link is not working again

**Comment by webmaven** [comment]
@JasperSnoek, How about just linking to [your GitHub account](https://github.com/JasperSnoek), instead?
