### ISSUE TITLE
crashes after 128 complete jobs on any function

### ISSUE THREAD

**Issue by szubair-nara** [JasperSnoek/spearmint#47]
Any idea why spearmint is crashing after 128 complete jobs on any function? 

Process:               Python [24424]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.6 (2.7.6)
Code Type:             X86-64 (Native)
Parent Process:        Python [13605]
Responsible:           Terminal [283]
User ID:               502

Date/Time:             2015-09-24 17:01:53.077 -0400
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        C8101117-3DE0-A245-4B6A-459E30D764AF

Time Awake Since Boot: 3000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000110

**Comment by JasperSnoek** [comment]
Hi @szubair-nara, that's really strange!  I don't think this has been an issue before and I'm pretty sure it would've come up.  Can you possibly try on another machine and see if it's still happening?

**Comment by szubair-nara** [comment]
So I have tried it on another machine - though it was not very useful as I am using mac osx on both machines... I have a hunch it has to do with numpy/scipy linking to the accelerate framework (mac osx specific blas) along with some bug about multiprocessing.

**Comment by szubair-nara** [comment]
http://pastebin.com/hTkpmM20

**Comment by JasperSnoek** [comment]
Hmm that's strange!  Can you try running spearmint without multiprocessing `-method-args=use_multiprocessing=0`

**Comment by szubair-nara** [comment]
that fixed it - also using numpy compiled with openblas in a virtual machine fixed it for me as well. Thanks so much for the help!!
