### ISSUE TITLE
Converging condition

### ISSUE THREAD

**Issue by Nitti121** [JasperSnoek/spearmint#54]
Hi, I am new to spearmint. Can anyone help me regarding two things. As I have run the branin example. Do we have to provide some stopping condition or stop it manually?...as it is keeps on running...
Secondly, about the objective function....

**Comment by JasperSnoek** [comment]
See https://github.com/JasperSnoek/spearmint/issues/53.

What about the objective function?

**Comment by Nitti121** [comment]
Thanks for your reply...
As I only know the parameters and their ranges...the function is known...It is possible to run spearmint in this case..?...If yes then what function should I write in wrapper file?

**Comment by Nitti121** [comment]
# the function is unknown

**Comment by JasperSnoek** [comment]
I'm not sure I understand the question.  What is the function you're optimizing?  I assume you must be able to evaluate the function right?
