### ISSUE TITLE
specifying the number of initial points in Spearmint

### ISSUE THREAD

**Issue by ntienvu** [JasperSnoek/spearmint#60]
Hi There,
I am Vu Nguyen from Deakin University, Australia.
I want to use Spearmint as a baseline for my paper. I want to set the number of initial points (e.g., at the beginning of the Bayesian Optimization procedure). I assume this can be done in the config.json. However, I can specify the "max_finished_jobs", but not the # initial points.
Please help me.
Regards,
Vu

**Comment by JasperSnoek** [comment]
Hey @ntienvu, this code is a bit dated now and probably isn't the best baseline to compare to (e.g. https://github.com/HIPS/Spearmint is more up to date - particularly the PESC branch).  However, the flag --grid-size will do this for you (https://github.com/JasperSnoek/spearmint/blob/master/spearmint/spearmint/main.py#L83).

**Comment by JasperSnoek** [comment]
Sorry and you can use spearmint-lite to initialize the experiment with whatever results you would like (just edit the flat file).

**Comment by ntienvu** [comment]
Thanks JasperSnoeak for your answer. I will try PESC branch.
Cheers,
