### ISSUE TITLE
Reasons why program is printing out, but not finding any best candidates?

### ISSUE THREAD

**Issue by sarahwie** [JasperSnoek/spearmint#69]
I'm running the examples/branin code from a remote machine, after running it locally and getting proper results. I've checked that everything is installed exactly the same as it is locally, but when I run the code, I keep getting the same output, something like this: 

`----------------------------------------
Current best: No results returned yet.
19905 candidates   0 pending   0 complete
Choosing next candidate... 
selected job 95 from the grid.
Submitted job as process: 5963
submitted - pid = 5963

----------------------------------------
Current best: No results returned yet.
19904 candidates   0 pending   0 complete
Choosing next candidate... 
selected job 96 from the grid.
Submitted job as process: 6001
submitted - pid = 6001`

It doesn't seem to be finding any candidates whatsoever...does anyone have any suggestions for what could be causing this behavior?

**Comment by zlheui** [comment]
get same problem.

**Comment by sarahwie** [comment]
@zlheui Go into the logs or output subdirectory (can't remember the exact name) of Spearmint and vim the model files there. Spearmint prints errors there instead of to stdout!

**Comment by zlheui** [comment]
@sarahwie thanks, solved it by using protobuf version 2.5.0
